from pydantic import BaseModel, EmailStr, field_validator
from typing import Optional
from datetime import datetime
import uuid
from pydantic import Field

from backend_shared.utils.validation import sanitize_email, validate_password_strength

# Roles that belong to the admin portal (/admin/*). Everything else ("user",
# the default role for public self-registration) belongs to the site portal.
# Used both to gate admin-only role assignment (users router) and to keep
# login scoped to the right portal (auth router).
ADMIN_ROLES = {"super_admin", "editor", "broker"}


class UserBase(BaseModel):
    email: EmailStr
    name: Optional[str] = None
    role: Optional[str] = "user"
    region: Optional[str] = None
    country_code: Optional[str] = None
    referral_code: Optional[str] = None
    referred_by: Optional[str] = None
    # True right after a super_admin regenerates this account's password —
    # the admin portal forces a /admin/change-password stop before anything
    # else until it's cleared (see users.update_me()).
    must_change_password: bool = False
    # Stripe's own vocabulary (active/trialing/past_due/canceled/...), set
    # only by the /billing/webhook handler — read-only here, never accepted
    # by any *Update schema. "active" or "trialing" means the combined
    # Signals + Copy Trading subscription is unlocked.
    subscription_status: str = "inactive"


class User(UserBase):
    # the id is uuid4 auto generated by sqlalchemy
    id: uuid.UUID = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class UserSelfUpdate(BaseModel):
    """Fields a signed-in user (any role) may change about themselves.
    Deliberately excludes email (the account's primary key / identity) and
    role (admin-managed via the separate /users/{email}/role endpoint)."""

    name: Optional[str] = None
    current_password: Optional[str] = None
    new_password: Optional[str] = None

    @field_validator("new_password")
    @classmethod
    def _check_password_strength(cls, v):
        return validate_password_strength(v) if v is not None else v


class AdminUserCreate(BaseModel):
    """Used by super_admin to create a user directly (e.g. a client account),
    bypassing the public /auth/register flow and its MT5-account requirement."""

    email: EmailStr
    name: str
    password: str
    role: str = "client"
    referral_code: Optional[str] = None

    @field_validator("email", mode="before")
    @classmethod
    def _sanitize_email(cls, v):
        return sanitize_email(v) if isinstance(v, str) else v

    @field_validator("password")
    @classmethod
    def _check_password_strength(cls, v):
        return validate_password_strength(v)


class AdminUserUpdate(BaseModel):
    """Fields a super_admin may edit on any user record."""

    name: Optional[str] = None
    referral_code: Optional[str] = None
