from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime
import uuid
from pydantic import Field

# Roles that belong to the admin portal (/admin/*). Everything else ("user",
# the default role for public self-registration) belongs to the site portal.
# Used both to gate admin-only role assignment (users router) and to keep
# login scoped to the right portal (auth router).
ADMIN_ROLES = {"super_admin", "editor", "broker"}


class UserBase(BaseModel):
    email: EmailStr
    name: Optional[str] = None
    role: Optional[str] = "user"
    region: Optional[str] = None
    country_code: Optional[str] = None
    referral_code: Optional[str] = None
    referred_by: Optional[str] = None


class User(UserBase):
    # the id is uuid4 auto generated by sqlalchemy
    id: uuid.UUID = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class UserSelfUpdate(BaseModel):
    """Fields a signed-in user (any role) may change about themselves.
    Deliberately excludes email (the account's primary key / identity) and
    role (admin-managed via the separate /users/{email}/role endpoint)."""

    name: Optional[str] = None
    current_password: Optional[str] = None
    new_password: Optional[str] = Field(default=None, min_length=8)


class AdminUserCreate(BaseModel):
    """Used by super_admin to create a user directly (e.g. a client account),
    bypassing the public /auth/register flow and its MT5-account requirement."""

    email: EmailStr
    name: str
    password: str = Field(min_length=8)
    role: str = "client"
    referral_code: Optional[str] = None


class AdminUserUpdate(BaseModel):
    """Fields a super_admin may edit on any user record."""

    name: Optional[str] = None
    referral_code: Optional[str] = None
