from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime
import uuid
from pydantic import Field


class UserBase(BaseModel):
    email: EmailStr
    name: Optional[str] = None
    role: Optional[str] = "user"
    region: Optional[str] = None
    country_code: Optional[str] = None


class UserCreate(UserBase):
    password: str


class User(UserBase):
    # the id is uuid4 auto generated by sqlalchemy
    id: uuid.UUID = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
